### ISSUE TITLE
Feature-request: Mark days with Notes

### ISSUE THREAD

**Issue by thenoobtester** [dhunt84971/CalendarNotes#82]
Hi,

could it be possible to make days with notes visible on the calendar so we can see there is something to do?

Thank you very much for your help.

**Comment by dhunt84971** [comment]
Sorry for the delayed response.  I think I know what you are looking for, so any day that has notes recorded for that day would have a different color in the background?  Something like this:

![image](https://github.com/dhunt84971/CalendarNotes/assets/674065/37f64516-e528-44c7-9dc3-0a6bdb79d005)

Let me see what I can do.

**Comment by dhunt84971** [comment]
This feature was added with v1.1.19, but with a caveat.  Because the event that causes the days to highlight is based on the changing of the date, navigating to a different month using the buttons on the calendar does not cause the days to highlight.  The user must actually click on a day in that month to get the days to highlight.  A fix is being explored for this minor issue.
